// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#ifndef COMPLIANCE_ENGINE_CLI_PLAN_HPP
#define COMPLIANCE_ENGINE_CLI_PLAN_HPP

#include <CliOptions.hpp>
#include <Logging.h>
#include <Result.h>
#include <map>
#include <string>
#include <vector>

namespace ComplianceEngine
{
namespace Cli
{

// A plan rule's resolved mode. `parameters` isn't modelled yet: BenchmarkIO::
// Resource doesn't parse `parameterMetadata` yet (see its TODO), so plan/run
// can't pre-fill or validate per-rule overrides until that lands - every rule
// generated by `plan` today carries an empty `parameters` object, which `run`
// ignores.
//
// Both constructors are hand-written (not just brace-init) because this
// codebase targets C++11, where a default member initializer disqualifies a
// struct from aggregate initialization; the default one is kept explicit
// because ParsePlanFile default-constructs entries via std::map::operator[].
struct PlanRuleMode
{
    ToggleMode mode = ToggleMode::Audit;

    PlanRuleMode() = default;
    explicit PlanRuleMode(ToggleMode mode)
        : mode(mode)
    {
    }
};

// A parsed plan file's entry for one benchmark file (see docs/CLI.md's
// "plan / run" section and docs/payload-key-format.md \u00a77 for the on-disk
// JSON shape). Rules absent from `rules` are rules the plan author
// deliberately left out; `run` skips them. Keyed by `payloadKey` (the rule's
// opaque payload-key remainder, unique within this one file), not `section`
// - see docs/payload-key-format.md \u00a76.
struct PlanBenchmark
{
    std::string file;
    std::string name;
    std::string sha256;
    std::map<std::string, PlanRuleMode> rules;
};

// A parsed plan file: one or more benchmark entries. Each is independently
// scoped (own file, own sha256, own rules map) so a single plan can mix
// rules from multiple benchmark files (e.g. CIS + STIG) without copying rule
// content - see docs/payload-key-format.md \u00a77. `run` hard-fails the whole
// plan if any entry's file doesn't apply to the current host (no partial
// results from a mismatched entry).
struct Plan
{
    std::vector<PlanBenchmark> benchmarks;
};

// Computes the SHA-256 of a file's contents, hex-encoded lowercase. Applies
// the same input-hardening posture as benchmark-definition reads (path
// traversal / writable-parent-dir / O_NOFOLLOW / ownership checks) before
// hashing, since this reads root-run input.
Result<std::string> HashFile(const std::string& path, OsConfigLogHandle logHandle);

// Generates a plan for `benchmarkFile`: every rule is seeded at `audit`, then
// `toggles` (given by `section`, resolved internally to each rule's
// payloadKey) are applied in order (last write per rule wins). Returns the
// plan serialized as pretty JSON, wrapping a single-entry `benchmarks` array
// - combining plans from multiple files (docs/payload-key-format.md \u00a77) is
// currently a manual edit (concatenate `benchmarks` arrays), not a CLI
// feature yet. Fails if a toggle references a section the benchmark file
// doesn't have (fail-fast validation, see docs/CLI.md \u00a72).
Result<std::string> GeneratePlan(const std::string& benchmarkFile, const std::vector<Toggle>& toggles, OsConfigLogHandle logHandle);

// Parses a plan file from disk, applying the same input-hardening posture as
// benchmark-definition files (this is root-run input too).
Result<Plan> ParsePlanFile(const std::string& path, OsConfigLogHandle logHandle);

} // namespace Cli
} // namespace ComplianceEngine
#endif // COMPLIANCE_ENGINE_CLI_PLAN_HPP
