// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#ifndef COMPLIANCE_ENGINE_CLI_PLAN_HPP
#define COMPLIANCE_ENGINE_CLI_PLAN_HPP

#include <CliOptions.hpp>
#include <Logging.h>
#include <Result.h>
#include <map>
#include <string>
#include <vector>

namespace ComplianceEngine
{
namespace Cli
{

// A plan rule's resolved mode. `parameters` isn't modelled yet: BenchmarkIO::
// Resource doesn't parse `parameterMetadata` yet (see its TODO), so plan/run
// can't pre-fill or validate per-rule overrides until that lands - every rule
// generated by `plan` today carries an empty `parameters` object, which `run`
// ignores.
//
// Both constructors are hand-written (not just brace-init) because this
// codebase targets C++11, where a default member initializer disqualifies a
// struct from aggregate initialization; the default one is kept explicit
// because ParsePlanFile default-constructs entries via std::map::operator[].
struct PlanRuleMode
{
    ToggleMode mode = ToggleMode::Audit;

    PlanRuleMode() = default;
    explicit PlanRuleMode(ToggleMode mode)
        : mode(mode)
    {
    }
};

// A parsed plan file (see docs/CLI.md's "plan / run" section for the on-disk
// JSON shape). Rules absent from `rules` are rules the plan author
// deliberately left out; `run` skips them.
struct Plan
{
    std::string benchmarkFile;
    std::string benchmarkName;
    std::string benchmarkSha256;
    std::map<std::string, PlanRuleMode> rules;
};

// Computes the SHA-256 of a file's contents, hex-encoded lowercase. Applies
// the same input-hardening posture as benchmark-definition reads (path
// traversal / writable-parent-dir / O_NOFOLLOW / ownership checks) before
// hashing, since this reads root-run input.
Result<std::string> HashFile(const std::string& path, OsConfigLogHandle logHandle);

// Generates a plan for `benchmarkFile`: every rule is seeded at `audit`, then
// `toggles` are applied in order (last write per section wins). Returns the
// plan serialized as pretty JSON. Fails if a toggle references a section the
// benchmark file doesn't have (fail-fast validation, see docs/CLI.md \u00a72).
Result<std::string> GeneratePlan(const std::string& benchmarkFile, const std::vector<Toggle>& toggles, OsConfigLogHandle logHandle);

// Parses a plan file from disk, applying the same input-hardening posture as
// benchmark-definition files (this is root-run input too).
Result<Plan> ParsePlanFile(const std::string& path, OsConfigLogHandle logHandle);

} // namespace Cli
} // namespace ComplianceEngine
#endif // COMPLIANCE_ENGINE_CLI_PLAN_HPP
